### ISSUE TITLE
Deprecation warnings abound

### ISSUE THREAD

**Issue by atz** [projectblacklight/spotlight#1479]
```
DEPRECATION WARNING: The assertion was not run because of an invalid css selector.
unexpected '?' after 'equal' (called from block (3 levels) in <module:Spotlight> at /home/travis/build/projectblacklight/spotlight/spec/views/spotlight/roles/index.html.erb_spec.rb:21)
DEPRECATION WARNING: The assertion was not run because of an invalid css selector.
unexpected '?' after 'equal' (called from block (3 levels) in <module:Spotlight> at /home/travis/build/projectblacklight/spotlight/spec/views/spotlight/roles/index.html.erb_spec.rb:22)
DEPRECATION WARNING: The assertion was not run because of an invalid css selector.
unexpected '?' after 'equal' (called from block (3 levels) in <module:Spotlight> at /home/travis/build/projectblacklight/spotlight/spec/views/spotlight/roles/index.html.erb_spec.rb:23)
DEPRECATION WARNING: The assertion was not run because of an invalid css selector.
unexpected '?' after 'equal' (called from block (3 levels) in <module:Spotlight> at /home/travis/build/projectblacklight/spotlight/spec/views/spotlight/roles/index.html.erb_spec.rb:24)
DEPRECATION WARNING: render_index_field_value is deprecated and will be removed from Blacklight version 7.0.0 (replaced by IndexPresenter#field_value). (called from block (2 levels) in __home_travis_build_projectblacklight_spotlight_app_views_spotlight_sir_trevor_blocks__solr_documents_features_block_html_erb___2444369124645355373_133428260 at /home/travis/build/projectblacklight/spotlight/app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb:21)
DEPRECATION WARNING: render_field_value is deprecated and will be removed from Blacklight version 7.0.0 (replaced by IndexPresenter#field_value). (called from render_index_field_value at /home/travis/.rvm/gems/ruby-2.3.1/gems/blacklight-6.3.1/app/helpers/blacklight/blacklight_helper_behavior.rb:165)
......
==== DEPRECATION WARNINGS ====
DEPRECATION WARNING: render_index_field_value is deprecated and will be removed from Blacklight version 7.0.0 (replaced by IndexPresenter#field_value). (called from block (2 levels) in __home_travis_build_projectblacklight_spotlight_app_views_spotlight_sir_trevor_blocks__solr_documents_features_block_html_erb___2444369124645355373_133428260 at /home/travis/build/projectblacklight/spotlight/app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb:21) (6 times); e.g.: 
    /home/travis/build/projectblacklight/spotlight/app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb:21:in `block (2 levels) in __home_travis_build_projectblacklight_spotlight_app_views_spotlight_sir_trevor_blocks__solr_documents_features_block_html_erb___2444369124645355373_133428260'
    /home/travis/.rvm/gems/ruby-2.3.1/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
    /home/travis/.rvm/gems/ruby-2.3.1/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
    /home/travis/.rvm/gems/ruby-2.3.1/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb:38:in `capture'
    /home/travis/build/projectblacklight/spotlight/app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb:19:in `block in __home_travis_build_projectblacklight_spotlight_app_views_spotlight_sir_trevor_blocks__solr_documents_features_block_html_erb___2444369124645355373_133428260'
DEPRECATION WARNING: render_field_value is deprecated and will be removed from Blacklight version 7.0.0 (replaced by IndexPresenter#field_value). (called from render_index_field_value at /home/travis/.rvm/gems/ruby-2.3.1/gems/blacklight-6.3.1/app/helpers/blacklight/blacklight_helper_behavior.rb:165) (6 times); e.g.: 
    /home/travis/.rvm/gems/ruby-2.3.1/gems/blacklight-6.3.1/app/helpers/blacklight/blacklight_helper_behavior.rb:165:in `render_index_field_value'
    /home/travis/build/projectblacklight/spotlight/app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb:21:in `block (2 levels) in __home_travis_build_projectblacklight_spotlight_app_views_spotlight_sir_trevor_blocks__solr_documents_features_block_html_erb___2444369124645355373_133428260'
    /home/travis/.rvm/gems/ruby-2.3.1/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
    /home/travis/.rvm/gems/ruby-2.3.1/gems/actionview-
...
--------------------------------------------------------------------------------
CarrierWave::Test::Matchers::BeNoLargerThan implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
(Used from /home/travis/build/projectblacklight/spotlight/spec/uploaders/spotlight/item_uploader_spec.rb:35
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
CarrierWave::Test::Matchers::HaveDimensions implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
(Used from /home/travis/build/projectblacklight/spotlight/spec/uploaders/spotlight/item_uploader_spec.rb:29
--------------------------------------------------------------------------------
```

The invalid CSS selectors seem like potentially the most serious of the set.

**Comment by jcoyne** [comment]
The CarrierWave related ones are due to https://github.com/carrierwaveuploader/carrierwave/issues/1437
