### ISSUE TITLE
Status bar display for "add item" has disappeared

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1751]

**Comment by caaster** [comment]
I am still seeing this behavior, when I go to the following unpublished exhibit in prod: (feel free to experiment/poke at this exhibit; I use it for testing): https://exhibits.stanford.edu/reid-dennis/catalog/admin. The status bar definitely does not appear when I do a full reindex of all items.

**Comment by cbeer** [comment]
It looks like a data problem in the exhibit (and hasn't timed out yet(?), so it hasn't been reported to honeybadger):

```
Performed Spotlight::ReindexJob from Sidekiq(default) in 62407.45ms
ActiveRecord::RecordNotFound: Couldn't find Spotlight::FeaturedImage without an ID
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:456:in `find_with_ids'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:66:in `find'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.1/lib/active_record/querying.rb:3:in `find'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.1/lib/active_record/core.rb:151:in `find'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/blacklight-spotlight-0.34.0/app/services/spotlight/carrierwave_file_resolver.rb:5:in `pattern'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/riiif-1.1.0/lib/riiif/abstract_file_system_resolver.rb:17:in `path'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/riiif-1.1.0/lib/riiif/abstract_file_system_resolver.rb:11:in `find'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/riiif-1.1.0/app/models/riiif/image.rb:32:in `image'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/riiif-1.1.0/app/models/riiif/image.rb:45:in `info'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/blacklight-spotlight-0.34.0/app/services/spotlight/upload_solr_document_builder.rb:23:in `add_image_dimensions'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/blacklight-spotlight-0.34.0/app/services/spotlight/upload_solr_document_builder.rb:9:in `block in to_solr'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/blacklight-spotlight-0.34.0/app/services/spotlight/upload_solr_document_builder.rb:7:in `tap'
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.4.0/gems/blacklight-spotlight-0.34.0/app/services/spotlight/upload_solr_document_builder.rb:7:in `to_solr'
```

**Comment by jkeck** [comment]
@cbeer yeah, looking over the original code, the relationships for uploads changed (which I thought was the pattern that stayed the same).  We need to add that to the migration code.
