### ISSUE TITLE
Question: shouldn't taggable_id of table taggings be of type integer

### ISSUE THREAD

**Issue by wwelling** [projectblacklight/spotlight#1756]
https://github.com/TAMULib/spotlight/blob/tamu-spotlight/db/migrate/20140206152809_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb

```
t.string :taggable_id
```

Shouldn't this be:

```
t.integer :taggable_id
```

**Comment by jkeck** [comment]
@wwelling is there some sort of problem that you're seeing that's caused by the use of a string instead of an integer?

FWIW, this migration comes from the ActsAsTaggableOn gem, and wasn't necessarily hand-written by us.

**Comment by cbeer** [comment]
I think we did  customize their migration to make it work with `SolrDocument` instances:

https://github.com/projectblacklight/spotlight/commit/57775d479a974fb214a413cc443907d489bada24

So, no, this was intentional.

**Comment by wwelling** [comment]
Yes, it throws a type cast exception in a query where taggable_id is in a subquery that has a result set of integer ids. I can get the stack trace if need be. I made the change to integer type a while ago in our customizations.

**Comment by wwelling** [comment]
```
F, [2017-02-15T16:57:44.013333 #30385] FATAL -- : [87ce29ec-0cc5-45ae-8f87-83f28e233cff]   
F, [2017-02-15T16:57:44.013367 #30385] FATAL -- : [87ce29ec-0cc5-45ae-8f87-83f28e233cff] ActionView::Template::Error (PG::UndefinedFunction: ERROR:  operator does not exist: character varying = integer
LINE 1: ...= 'Spotlight::Exhibit') AND (taggings.taggable_id IN(SELECT ...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT COUNT(*) FROM "tags" JOIN (SELECT taggings.tag_id FROM "taggings" WHERE (taggings.taggable_type = 'Spotlight::Exhibit') AND (taggings.taggable_id IN(SELECT spotlight_exhibits.id FROM "spotlight_exhibits" WHERE ('t'='t') AND "spotlight_exhibits"."published" = 't')) GROUP BY taggings.tag_id) AS taggings ON taggings.tag_id = tags.id):
F, [2017-02-15T16:57:44.013468 #30385] FATAL -- : [87ce29ec-0cc5-45ae-8f87-83f28e233cff]     1: <% if tags.any? %>
[87ce29ec-0cc5-45ae-8f87-83f28e233cff]     2: <div class="row">
[87ce29ec-0cc5-45ae-8f87-83f28e233cff]     3:   <div class="col-md-12 text-center">
[87ce29ec-0cc5-45ae-8f87-83f28e233cff]     4:     <ul class="nav nav-pills tags">
F, [2017-02-15T16:57:44.013499 #30385] FATAL -- : [87ce29ec-0cc5-45ae-8f87-83f28e233cff]   
F, [2017-02-15T16:57:44.013535 #30385] FATAL -- : [87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:93:in `block in select_all'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:108:in `cache_sql'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:93:in `select_all'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/relation/calculations.rb:248:in `execute_simple_calculation'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/relation/calculations.rb:207:in `perform_calculation'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/relation/calculations.rb:121:in `calculate'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/relation/calculations.rb:40:in `count'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] acts-as-taggable-on (4.0.0) lib/acts_as_taggable_on/taggable/collection.rb:177:in `count'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/relation.rb:285:in `empty?'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/relation.rb:299:in `any?'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] /home/spotlight/spotlight/app/views/spotlight/exhibits/_tags.html.erb:1:in `__home_spotlight_spotlight_app_views_spotlight_exhibits__tags_html_erb___1875057928872138548_70248086509920'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/template.rb:159:in `block in render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/template.rb:354:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/template.rb:157:in `render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:310:in `render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/helpers/rendering_helper.rb:35:in `render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] /home/spotlight/spotlight/app/views/spotlight/exhibits/index.html.erb:19:in `__home_spotlight_spotlight_app_views_spotlight_exhibits_index_html_erb__614874776315816105_25672960'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/template.rb:159:in `block in render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/template.rb:354:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/template.rb:157:in `render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/renderer/renderer.rb:23:in `render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/rendering.rb:103:in `_render_template'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/rendering.rb:83:in `render_to_body'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/abstract_controller/rendering.rb:26:in `render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/rendering.rb:36:in `render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] /home/spotlight/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] /home/spotlight/spotlight/app/controllers/spotlight/exhibits_controller.rb:17:in `index'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] warden (1.2.7) lib/warden/manager.rb:35:in `catch'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] warden (1.2.7) lib/warden/manager.rb:35:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] rack (2.0.1) lib/rack/etag.rb:25:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] rack (2.0.1) lib/rack/head.rb:12:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] rack (2.0.1) lib/rack/method_override.rb:22:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] rack (2.0.1) lib/rack/runtime.rb:22:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] railties (5.0.1) lib/rails/engine.rb:522:in `call'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] /usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
[87ce29ec-0cc5-45ae-8f87-83f28e233cff] /usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```
