### ISSUE TITLE
The asset "spotlight/default_browse_thumbnail" is not present in the asset pipeline

### ISSUE THREAD

**Issue by nicolasfranck** [projectblacklight/spotlight#1884]
Situation:

* spotlight version 1.2.0
* using application with RAILS_ENV set to "production"
* pre generated compiled assets

Problem:

When I visit the "browse" page (Spotlight::BrowseController#index), I got this error:

```
ActionView::Template::Error (The asset "spotlight/default_browse_thumbnail" is not present in the asset pipeline.):
F, [2018-01-15T10:13:50.147166 #68710] FATAL -- : [f5d0fc27-d5ec-42dd-a384-810d140b5429]     2:   <div class="col-sm-4 col-xs-12 category">
[f5d0fc27-d5ec-42dd-a384-810d140b5429]     3:     <%= link_to spotlight.exhibit_browse_path(@exhibit, search) do %>
[f5d0fc27-d5ec-42dd-a384-810d140b5429]     4:       <div class="image-overlay">
[f5d0fc27-d5ec-42dd-a384-810d140b5429]     5:         <%= image_tag(search.thumbnail_image_url || 'spotlight/default_browse_thumbnail', class: 'img-responsive') %>
[f5d0fc27-d5ec-42dd-a384-810d140b5429]     6:         <div class="text-overlay">
[f5d0fc27-d5ec-42dd-a384-810d140b5429]     7:            <h2 class="browse-category-title">
[f5d0fc27-d5ec-42dd-a384-810d140b5429]     8:              <%= search.title%>
F, [2018-01-15T10:13:50.147527 #68710] FATAL -- : [f5d0fc27-d5ec-42dd-a384-810d140b5429]   
F, [2018-01-15T10:13:50.148074 #68710] FATAL -- : [f5d0fc27-d5ec-42dd-a384-810d140b5429] sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:83:in `compute_asset_path'
[f5d0fc27-d5ec-42dd-a384-810d140b5429] actionview (5.1.4) lib/action_view/helpers/asset_url_helper.rb:198:in `asset_path'
[f5d0fc27-d5ec-42dd-a384-810d140b5429] actionview (5.1.4) lib/action_view/helpers/asset_url_helper.rb:373:in `image_path'
[f5d0fc27-d5ec-42dd-a384-810d140b5429] actionview (5.1.4) lib/action_view/helpers/asset_tag_helper.rb:232:in `image_tag'
[f5d0fc27-d5ec-42dd-a384-810d140b5429] blacklight-spotlight (1.2.0) app/views/spotlight/browse/_search.html.erb:5:in `block (2 levels) in ___sers_njfranck__rvm_gems_ruby_______gems_blacklight_spotlight_______app_views_spotlight_browse__search_html_erb__923484506798189183_70233101695620'
```

The problem goes away when I change the configuration in config/environments/production.rb:

```
config.assets.compile = true
```

I could not test this against the latest version on github,  because there were conflicting packages in that version.

**Comment by mejackreed** [comment]
With sprockets >3.0 the extension is needed. I've added it in a PR here: https://github.com/projectblacklight/spotlight/pull/1895

**Comment by nicolasfranck** [comment]
@mejackreed Thanks!
