### ISSUE TITLE
Uploads won't reindex after running rake spotlight:migrate_to_iiif

### ISSUE THREAD

**Issue by travisLilleberg** [projectblacklight/spotlight#2101]
Hello,

I've run the rake spotlight:migrate_to_iiif, in order to get my site more up to date, but now reindexing is broken on all uploads. When I try to reindex an upload from the console I get:

`ArgumentError: Invalid characters in id `1373`
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/riiif-1.5.0/lib/riiif/file_system_file_resolver.rb:6:in `pattern'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/riiif-1.5.0/lib/riiif/abstract_file_system_resolver.rb:17:in `path'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/riiif-1.5.0/lib/riiif/abstract_file_system_resolver.rb:11:in `find'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/riiif-1.5.0/app/models/riiif/image.rb:49:in `image'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/riiif-1.5.0/app/models/riiif/image.rb:63:in `info'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/bundler/gems/spotlight-3973dd4cd068/app/services/spotlight/upload_solr_document_builder.rb:23:in `add_image_dimensions'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/bundler/gems/spotlight-3973dd4cd068/app/services/spotlight/upload_solr_document_builder.rb:9:in `block in to_solr'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/bundler/gems/spotlight-3973dd4cd068/app/services/spotlight/upload_solr_document_builder.rb:7:in `tap'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/bundler/gems/spotlight-3973dd4cd068/app/services/spotlight/upload_solr_document_builder.rb:7:in `to_solr'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/bundler/gems/spotlight-3973dd4cd068/app/services/spotlight/solr_document_builder.rb:14:in `documents_to_index'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/bundler/gems/spotlight-3973dd4cd068/app/models/spotlight/resource.rb:52:in `block (2 levels) in reindex'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:126:in `call'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_index_callbacks'
... 10 levels...
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /usr/local/hydra/spotlight/bin/rails:9:in `<top (required)>'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
	from /home/hydradm/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/hydradm/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'`

Looking at the code, the error is coming from this line in the FileSystemResolver:

`raise ArgumentError, "Invalid characters in id `#{id}`" unless id =~ /^[\w\-:]+$/`

When I manually run this check, it returns `nil` because the id is an integer and integers appear to always return nil when applied to regex.

Thanks.

**Comment by travisLilleberg** [comment]
I've gotten closer, for some reason my environment is using `Riiif::FileSystemFileResolver`:

```ruby
2.4.2 :001 > Riiif::Image.file_resolver
 => #<Riiif::FileSystemFileResolver:0x0000000006b50f30 @root="/home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/riiif-1.5.0", @base_path="/home/hydradm/.rvm/gems/ruby-2.4.2@tufts-spotlight/gems/riiif-1.5.0/spec/samples"> 
```

Despite the fact that I have this in my initializers/riiif.rb
`Riiif::Image.file_resolver = Spotlight::CarrierwaveFileResolver.new `

**Comment by jkeck** [comment]
Gah, Spring strikes again.  Thanks for reporting back.
