### ISSUE TITLE
problem with setting up production on Apache with Passenger

### ISSUE THREAD

**Issue by whisere** [projectblacklight/spotlight#2136]
I have tried to set up Apache with Passenger to replace rails server. It works on development
When I use RailsEnv development under Apache conf file
When I tried to change it to RailsEnv production, run into the following problems:

I have created the secret.yml and run
bundle exec rake assets:precompile db:migrate RAILS_ENV=production

It reported:
== 20180814221815 ChangePaperTrailVersionsObjectColumnToMediumText: migrating =
-- adapter_name()
   -> 0.0000s
-- change_column(:versions, :object, :text, {:limit=>1073741823})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

**Could not find table 'versions'**
/Users/user/Documents/spotlight/db/migrate/20180814221815_change_paper_trail_versions_object_column_to_medium_text.rb:9:in `change'
/Users/user/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Could not find table 'versions'
/Users/user/Documents/spotlight/db/migrate/20180814221815_change_paper_trail_versions_object_column_to_medium_text.rb:9:in `change'
/Users/user/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
    
then go to spotlight home:
    
    App 9109 output:     /Users/user/.rvm/gems/ruby-2.5.1/gems/passenger-6.0.1/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 9109 output:     /Users/user/.rvm/gems/ruby-2.5.1/gems/passenger-6.0.1/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
App 9109 output:     /Users/user/.rvm/gems/ruby-2.5.1/gems/passenger-6.0.1/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 9109 output:     /Users/user/.rvm/gems/ruby-2.5.1/gems/passenger-6.0.1/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 9109 output:     /Users/user/.rvm/gems/ruby-2.5.1/gems/passenger-6.0.1/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2019-02-18 15:09:33.7124 9097/Tr age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /Applications/MAMP/htdocs/spotlight: The application encountered the following error: **Could not find table 'spotlight_pages'** (ActiveRecord::StatementInvalid)
  Error ID: e69f67a3
  Error details saved to: /tmp/passenger-error-BPG9QA.html

[ E 2019-02-18 15:09:33.7195 9097/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is e69f67a3. Please see earlier logs for details about the error.
    
Any suggestions are much appreciated! Thanks.

**Comment by whisere** [comment]
I am wondering if I should just copy the development.sqlite3 to production.sqlite3 since its the database tables that it can't find.

**Comment by jkeck** [comment]
It would not be recommended to use sqlite in production.

Have you tried running the `db:migrate` task before the `assets:precompile` task?

**Comment by whisere** [comment]
I just tried db:migrate first with
bundle exec rake db:migrate RAILS_ENV=production

but still getting this error 
DEPRECATION WARNING: Initializing a file resolver without setting the base path is deprecated and will be removed in Riiif 2.0. (called from new at /Users/junran/Documents/acr/spotlight_production/config/initializers/riiif.rb:1)
== 20180814221815 ChangePaperTrailVersionsObjectColumnToMediumText: migrating =
-- adapter_name()
   -> 0.0000s
-- change_column(:versions, :object, :text, {:limit=>1073741823})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Could not find table 'versions'
/Users/junran/Documents/acr/spotlight_production/db/migrate/20180814221815_change_paper_trail_versions_object_column_to_medium_text.rb:9:in `change'
/Users/junran/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/junran/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/junran/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Could not find table 'versions'
/Users/junran/Documents/acr/spotlight_production/db/migrate/20180814221815_change_paper_trail_versions_object_column_to_medium_text.rb:9:in `change'
/Users/junran/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/junran/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/junran/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by jkeck** [comment]
It sounds like you're missing migration files in your application.  (Perhaps you needed to run `rake spotlight:install:migrations` at some point)

Take a look at your migrations and schema and compare them to what Spotlight provides and see if there is something missing.

**Comment by whisere** [comment]
Thank you! @jkeck I have  tried 

bundle exec rake spotlight:install:migrations
bundle exec rake db:migrate

**bundle exec rake spotlight:install:migrations**
DEPRECATION WARNING: Initializing a file resolver without setting the base path is deprecated and will be removed in Riiif 2.0. (called from new at /Users/user/Documents/acr/spotlight_production/config/initializers/riiif.rb:1)

**bundle exec rake db:migrate**
DEPRECATION WARNING: Initializing a file resolver without setting the base path is deprecated and will be removed in Riiif 2.0. (called from new at /Users/user/Documents/acr/spotlight_production/config/initializers/riiif.rb:1)
D, [2019-02-26T09:52:49.056249 #3072] DEBUG -- :    (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2019-02-26T09:52:49.056433 #3072] DEBUG -- :   ↳ /Users/user/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271
D, [2019-02-26T09:52:49.059318 #3072] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.7ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2019-02-26T09:52:49.059454 #3072] DEBUG -- :   ↳ /Users/user/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271
D, [2019-02-26T09:52:49.063377 #3072] DEBUG -- :    (0.1ms)  begin transaction
D, [2019-02-26T09:52:49.063478 #3072] DEBUG -- :   ↳ /Users/user/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271
D, [2019-02-26T09:52:49.064186 #3072] DEBUG -- :    (0.0ms)  commit transaction
D, [2019-02-26T09:52:49.064303 #3072] DEBUG -- :   ↳ /Users/user/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271
D, [2019-02-26T09:52:49.065571 #3072] DEBUG -- :    (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2019-02-26T09:52:49.065658 #3072] DEBUG -- :   ↳ /Users/user/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271

**Then run
bundle exec rake db:migrate RAILS_ENV=production**
But still reported can't find Version table
DEPRECATION WARNING: Initializing a file resolver without setting the base path is deprecated and will be removed in Riiif 2.0. (called from new at /Users/user/Documents/acr/spotlight_production/config/initializers/riiif.rb:1)
== 20180814221815 ChangePaperTrailVersionsObjectColumnToMediumText: migrating =
-- adapter_name()
   -> 0.0000s
-- change_column(:versions, :object, :text, {:limit=>1073741823})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Could not find table 'versions'
/Users/user/Documents/acr/spotlight_production/db/migrate/20180814221815_change_paper_trail_versions_object_column_to_medium_text.rb:9:in `change'
/Users/user/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Could not find table 'versions'
/Users/user/Documents/acr/spotlight_production/db/migrate/20180814221815_change_paper_trail_versions_object_column_to_medium_text.rb:9:in `change'
/Users/user/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by whisere** [comment]
Comparing the migration files, it has a 20180906033328_create_versions.rb in my files which is not in the github files
The content contains
# This migration creates the `versions` table, the only schema PT requires.
# All other migrations PT provides are optional.
class CreateVersions < ActiveRecord::Migration[5.2]

  # The largest text column available in all supported RDBMS is
  # 1024^3 - 1 bytes, roughly one gibibyte.  We specify a size
  # so that MySQL will use `longtext` instead of `text`.  Otherwise,
  # when serializing very large objects, `text` might not be big enough.
  TEXT_BYTES = 1_073_741_823

  def change
    create_table :versions do |t|
      t.string   :item_type, {:null=>false}
      t.integer  :item_id,   null: false
      t.string   :event,     null: false
      t.string   :whodunnit
      t.text     :object, limit: TEXT_BYTES

      # Known issue in MySQL: fractional second precision
      # -------------------------------------------------
      #
      # MySQL timestamp columns do not support fractional seconds unless
      # defined with "fractional seconds precision". MySQL users should manually
      # add fractional seconds precision to this migration, specifically, to
      # the `created_at` column.
      # (https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html)
      #
      # MySQL users should also upgrade to at least rails 4.2, which is the first
      # version of ActiveRecord with support for fractional seconds in MySQL.
      # (https://github.com/rails/rails/pull/14359)
      #
      t.datetime :created_at
    end
    add_index :versions, %i(item_type item_id)
  end
end

**Comment by whisere** [comment]
Other files missing from my migration are:
20140225180948_create_contact_emails


20140403180324_create_spotlight_main_navigations.rb


20141117111311_create_locks.rb


20150410180014_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine

but has 20180906033369_add_taggings_counter_cache_to_tags.spotlight


20150410180015_add_missing_taggable_index.acts_as_taggable_on_engine

but has 20180906033370_add_missing_taggable_index.spotlight


20150410180016_change_collation_for_tag_names.acts_as_taggable_on_engine

but has 20180906033371_change_collation_for_tag_names.spotlight

should I copy them across? Thank you!

**Comment by whisere** [comment]
I can see the versions table in development.sqlite3 though.
