### ISSUE TITLE
Missing rdoc dependency

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#2150]
```./bin/rails console -e production
/home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require': cannot load such file -- rdoc (LoadError)
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:80:in `register'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:36:in `rescue in require'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:25:in `require'
	from /home/ec2-user/.gem/ruby/2.4/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/ec2-user/.gem/ruby/2.4/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/ec2-user/.gem/ruby/2.4/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from /home/ec2-user/.gem/ruby/2.4/gems/github-markup-3.0.3/lib/github/markup/rdoc.rb:2:in `<main>'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/ec2-user/.gem/ruby/2.4/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/ec2-user/.gem/ruby/2.4/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/ec2-user/.gem/ruby/2.4/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from /home/ec2-user/.gem/ruby/2.4/gems/github-markup-3.0.3/lib/github/markups.rb:2:in `<module:Markup>'
	from /home/ec2-user/.gem/ruby/2.4/gems/github-markup-3.0.3/lib/github/markup.rb:101:in `instance_eval'
	from /home/ec2-user/.gem/ruby/2.4/gems/github-markup-3.0.3/lib/github/markup.rb:101:in `<module:Markup>'
	from /home/ec2-user/.gem/ruby/2.4/gems/github-markup-3.0.3/lib/github/markup.rb:25:in `<module:GitHub>'
	from /home/ec2-user/.gem/ruby/2.4/gems/github-markup-3.0.3/lib/github/markup.rb:10:in `<main>'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/ec2-user/.gem/ruby/2.4/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/ec2-user/.gem/ruby/2.4/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/ec2-user/.gem/ruby/2.4/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/ec2-user/.gem/ruby/2.4/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from /home/ec2-user/.gem/ruby/2.4/gems/blacklight-spotlight-2.4.1/lib/spotlight/engine.rb:36:in `<class:Engine>'
	from /home/ec2-user/.gem/ruby/2.4/gems/blacklight-spotlight-2.4.1/lib/spotlight/engine.rb:22:in `<module:Spotlight>'
	from /home/ec2-user/.gem/ruby/2.4/gems/blacklight-spotlight-2.4.1/lib/spotlight/engine.rb:18:in `<main>'
```

**Comment by jcoyne** [comment]
This is resolved when I put `gem 'rdoc'` in my Gemfile.
