### ISSUE TITLE
rails/generators/actions.rb:26:in `gem': can't modifyfrozen String (RuntimeError)

### ISSUE THREAD

**Issue by traumschule** [projectblacklight/spotlight#2169]
```
$ rails new app-name -m https://raw.githubusercontent.com/projectblacklight/spotlight/master/template.rb
      create                                      
      create  README.rdoc                           
      create  Rakefile                                                                        
      create  config.ru                                                                                    
      create  .gitignore                                                                                   
      create  Gemfile                                                        
...
      create  vendor/assets/stylesheets/.keep
       apply  https://raw.githubusercontent.com/projectblacklight/spotlight/master/template.rb
/usr/lib/ruby/vendor_ruby/rails/generators/actions.rb:26:in `gem': can't modifyfrozen String (RuntimeError)
        from https://raw.githubusercontent.com/projectblacklight/spotlight/master/template.rb:11:in `apply'
        from /usr/lib/ruby/vendor_ruby/thor/actions.rb:223:in `instance_eval'
        from /usr/lib/ruby/vendor_ruby/thor/actions.rb:223:in `apply'
        from /usr/lib/ruby/vendor_ruby/rails/generators/app_base.rb:144:in `apply_rails_template'
        from (eval):1:in `apply_rails_template'
        from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
        from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:133:in `block in invoke_all'
        from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:133:in `each'
        from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:133:in `map'
        from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:133:in `invoke_all'
        from /usr/lib/ruby/vendor_ruby/thor/group.rb:232:in `dispatch'
        from /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
        from /usr/lib/ruby/vendor_ruby/rails/commands/application.rb:17:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/vendor_ruby/rails/cli.rb:14:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/bin/rails:9:in `<main>'
```

related to #2142 or #2167?

**Comment by traumschule** [comment]
It seems our versions are too old
- ruby 2.3.3p222 (2016-11-21)
- Rails 4.2.7.1
