### ISSUE TITLE
Wrong number of argument for search_state.

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#2920]
```
eval error: wrong number of arguments (given 3, expected 2)
  /Users/jcoyne85/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/blacklight-spotlight-3.6.0.beta1/lib/spotlight/search_state.rb:8:in `initialize'
  /Users/jcoyne85/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/blacklight-7.33.1/lib/blacklight/search_builder.rb:31:in `new'
  /Users/jcoyne85/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/blacklight-7.33.1/lib/blacklight/search_builder.rb:31:in `initialize'
  /Users/jcoyne85/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/blacklight-7.33.1/app/services/blacklight/search_service.rb:17:in `new'
  /Users/jcoyne85/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/blacklight-7.33.1/app/services/blacklight/search_service.rb:17:in `search_builder'
  (rdbg)//Users/jcoyne85/workspace/sul-dlss/dlme/app/models/statistics_dashboard.rb:1:in `search_builder'
```

It looks to me like our SearchState class should take three arguments in the initializer (https://github.com/projectblacklight/spotlight/blob/dcda37d33953412d11db82c91b6d5590e417c6cd/lib/spotlight/search_state.rb#L8)

as that is what it is called with here:
https://github.com/projectblacklight/blacklight/blob/v7.33.1/lib/blacklight/search_builder.rb#L31
https://github.com/projectblacklight/blacklight/blob/v7.33.1/app/services/blacklight/search_service.rb#L17

**Comment by jcoyne** [comment]
I was able to resolve this by replacing `include Blacklight::Searchable` with `include Spotlight::SearchHelper`
